---
title: "Part 1 Code"
format: html
editor: visual
---

To start, I'm going to put my API key here for safe keeping:

640ce0de32b08c9ded3cc11874a33ea9200c2c78

Now, to get our data from the Public Use Microdata Sample Census API.

```{r}
#| message: false
#| warning: false
#| echo: false
library(httr)
library(jsonlite)
library(tidyverse)
cen_data21<-GET("https://api.census.gov/data/2021/acs/acs1/pums?get=AGEP,GASP,GRPIP,JWAP,JWDP,JWMNP,PWGTP,FER,HHL,SCH,SCHL,SEX,ST,REGION,DIVISION&key=640ce0de32b08c9ded3cc11874a33ea9200c2c78")
```

```{r}
cen_data22<-GET("https://api.census.gov/data/2022/acs/acs1/pums?get=AGEP,GASP,GRPIP,JWAP,JWDP,JWMNP,PWGTP,FER,HHL,SCH,SCHL,SEX,ST,REGION,DIVISION&key=640ce0de32b08c9ded3cc11874a33ea9200c2c78")
```

```{r}
cen_data23<-GET("https://api.census.gov/data/2023/acs/acs1/pums?get=AGEP,GASP,GRPIP,JWAP,JWDP,JWMNP,PWGTP,FER,HHL,SCH,SCHL,SEX,STATE,REGION,DIVISION&key=640ce0de32b08c9ded3cc11874a33ea9200c2c78")
```

```{r}
cen_data24<-GET("https://api.census.gov/data/2024/acs/acs1/pums?get=AGEP,GASP,GRPIP,JWAP,JWDP,JWMNP,PWGTP,FER,HHL,SCH,SCHL,SEX,STATE,REGION,DIVISION&key=640ce0de32b08c9ded3cc11874a33ea9200c2c78")
```

```{r}
data_lists<-c(data21=cen_data21,data22=cen_data22, data23=cen_data23,data24=cen_data24)
saveRDS(data_lists,file="data/data_lists.rds")

```

```{r}
parsed21<-fromJSON(cen_data21$content)
cen21_info<-as_tibble(parsed21$data)
cen21_info
```
