---
title: "Variable Values"
format: html
editor: visual
---

```{r}
#| message: false
#| warning: false
#| echo: false
library(httr)
library(jsonlite)
library(tidyverse)
cen_vars21<-GET("https://api.census.gov/data/2021/acs/acs1/pums/variables.json?key=640ce0de32b08c9ded3cc11874a33ea9200c2c78")
parsed_vars21<-fromJSON(rawToChar(cen_vars21$content))
```


```{r}
vars21<-parsed_vars21$variables[c("AGEP","GASP","GRPIP","JWAP","JWDP","JWMNP","PWGTP","FER","HHL","SCH","SCHL","SEX","ST","REGION","DIVISION")]
```

```{r}
cen_vars22<-GET("https://api.census.gov/data/2022/acs/acs1/pums/variables.json?key=640ce0de32b08c9ded3cc11874a33ea9200c2c78")
parsed_vars22<-fromJSON(rawToChar(cen_vars22$content))
```


```{r}
vars22<-parsed_vars22$variables[c("AGEP","GASP","GRPIP","JWAP","JWDP","JWMNP","PWGTP","FER","HHL","SCH","SCHL","SEX","ST","REGION","DIVISION")]
```

```{r}
cen_vars23<-GET("https://api.census.gov/data/2023/acs/acs1/pums/variables.json?key=640ce0de32b08c9ded3cc11874a33ea9200c2c78")
parsed_vars23<-fromJSON(rawToChar(cen_vars23$content))
```


```{r}
vars23<-parsed_vars23$variables[c("AGEP","GASP","GRPIP","JWAP","JWDP","JWMNP","PWGTP","FER","HHL","SCH","SCHL","SEX","STATE","REGION","DIVISION")]
```

```{r}
cen_vars24<-GET("https://api.census.gov/data/2024/acs/acs1/pums/variables.json?key=640ce0de32b08c9ded3cc11874a33ea9200c2c78")
parsed_vars24<-fromJSON(rawToChar(cen_vars24$content))
```


```{r}
vars24<-parsed_vars24$variables[c("AGEP","GASP","GRPIP","JWAP","JWDP","JWMNP","PWGTP","FER","HHL","SCH","SCHL","SEX","STATE","REGION","DIVISION")]
```

At this point, for convenience later, I'm going to rename the state variables in vars21 and vars22 to match the other years.

```{r}
vars21$STATE<-vars21$ST
vars22$STATE<-vars22$ST
```

Now, to avoid confusion, I'll remove the "ST" lists from vars21 & vars22:

```{r}
vars21$ST<-NULL
vars22$ST<-NULL
```

